### ISSUE TITLE
Feature Asalto: Fin del asalto.

### ISSUE THREAD

**Issue by tbanjos** [tripledes/thesheriff#25]
e-mail a los miembros de la banda con:
Score de la banda
Puntuación del Sheriff en el asalto.

**Comment by tbanjos** [comment]
una consulta: que seria el score de la banda?

**Comment by tripledes** [comment]
> Una consulta: que seria el score de la banda? Me imagino que es la suma de la puntuación de los miembros.

Creo que como dices es la suma de la puntuación.
