### ISSUE TITLE
Feature Bandas: Buscar bandas a las que pertenecen a un amigo (desde el listado de amigos)

### ISSUE THREAD

**Issue by rmuhamed** [tripledes/thesheriff#65]

**Comment by rmuhamed** [comment]
I guess this one is achievable from **list friends** , we get a friend id, and then, through **list gangs** using the friend's id so we have the gangs he is part from

Am I right?

**Comment by tripledes** [comment]
> I guess this one is achievable from **list friends** , we get a friend id, and then, through **list gangs** using the friend's id so we have the gangs he is part from
> 
> Am I right? @tripledes @Quimnadalsalle @diegozavsalle @tbanjos

I think so, sounds like a bit of overlapping in fact.

**Comment by rmuhamed** [comment]
So, lets close it
