### ISSUE TITLE
Refactoring y documentación de las tecnicas usadas.

### ISSUE THREAD

**Issue by rmuhamed** [tripledes/thesheriff#69]

**Comment by tripledes** [comment]
As a note here, I do think we can produce everything with sphinx, allow me to explain.

This is just one example on what we can produce with sphinx just using RST (I think it also takes MD) files:

* Result: https://2.python-requests.org/en/master/
* Code: https://github.com/psf/requests/tree/master/docs

I'm trying to layout an example with better organize structure, once #68 and #67 are merged I'll try to send over my local branch for you all to see.

That being said, I'm happy to use Asciidoc, Markdown, Gdocs...you pick! :rocket:

**Comment by tbanjos** [comment]
Sphinx seems like a nice choice

**Comment by rmuhamed** [comment]
Related issue #116
