### ISSUE TITLE
[Proposal] unifiy how to return responses from endpoints

### ISSUE THREAD

**Issue by tripledes** [tripledes/thesheriff#92]
* Both `make_response` and `jsonify` return flask.Response object.
* Response object already adds an HTTP code status code (add -vv to curl to see it)
* `make_response` vs `jsonify`:
  * `make_response` needs the help of `json.dumps` and we are importing the json module plus `make_response`.
  * `jsonify` already serializes the objects itself, it only needs the right data structure.

So I'd say we go the `jsonify` route and return no statuses, if we need to handle headers, errors or so I think it can all be done with `flask.Response`.

**Comment by rmuhamed** [comment]
So no make_response :(?

**Comment by tbanjos** [comment]
Fine by me. I'll see if is there any place still with make_response and change it

**Comment by tripledes** [comment]
Thanks!
